server:
  port: 8081
  servlet:
    context-path: /portal/v1
spring:
  application:
    name: portal-service
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/v1/eureka/
  instance:
    prefer-ip-address: true